/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 21 07:16:45 GMT 2023
 */

package soj.biclique;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.storm.kafka.spout.KafkaSpoutRetryService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import soj.biclique.KafkaTopology;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KafkaTopology_ESTest extends KafkaTopology_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KafkaSpoutRetryService kafkaSpoutRetryService0 = KafkaTopology.getRetryService();
      assertNotNull(kafkaSpoutRetryService0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KafkaTopology kafkaTopology0 = new KafkaTopology();
  }
}
