/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 29 06:52:11 GMT 2023
 */

package com.algorand.algosdk.templates;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.algorand.algosdk.templates.HTLC;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HTLC_ESTest extends HTLC_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTLC.MakeHTLC((String) null, (String) null, (String) null, "ASAEBQEABiYDIP68oLsUSlpOp7Q4pGgayA5soQW8tgf8VlMlyVaV9qITAQYg5pqWHm8tX3rIZgeSZVK+mCNe0zNjyoiRi7nJOKkVtvkxASIOMRAjEhAxBzIDEhAxCCQSEDEJKBItASkSEDEJKhIxAiUNEBEQ", 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTLC.MakeHTLC("eL|`*", "eL|`*", "'ha456", "eL|`*", 98, 98);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // invalid hash function supplied
         //
         verifyException("com.algorand.algosdk.templates.HTLC", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTLC.MakeHTLC("sha256", "", "sha256", "sha256", (-4713), (-4713));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input string is an invalid address. Wrong length
         //
         verifyException("com.algorand.algosdk.crypto.Address", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTLC.MakeHTLC("", "", "keccak256", "", (-3699), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input string is an invalid address. Wrong length
         //
         verifyException("com.algorand.algosdk.crypto.Address", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HTLC hTLC0 = new HTLC();
  }
}
