/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 29 06:52:11 GMT 2023
 */

package com.algorand.algosdk.templates;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class HTLC_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.algorand.algosdk.templates.HTLC"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(HTLC_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.codec.binary.BaseNCodec",
      "org.apache.commons.codec.Encoder",
      "com.algorand.algosdk.templates.ContractTemplate$ParameterValue",
      "org.apache.commons.codec.BinaryEncoder",
      "org.apache.commons.codec.DecoderException",
      "org.apache.commons.codec.EncoderException",
      "com.algorand.algosdk.crypto.Signature",
      "com.algorand.algosdk.templates.ContractTemplate$1",
      "com.algorand.algosdk.templates.ContractTemplate$DataType",
      "org.apache.commons.codec.BinaryDecoder",
      "org.apache.commons.codec.binary.Base32",
      "com.algorand.algosdk.templates.ContractTemplate",
      "org.apache.commons.codec.binary.BaseNCodec$Context",
      "com.algorand.algosdk.crypto.Address",
      "org.apache.commons.codec.Decoder",
      "org.apache.commons.codec.binary.StringUtils",
      "org.apache.commons.codec.Charsets",
      "com.algorand.algosdk.templates.HTLC"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(HTLC_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.algorand.algosdk.templates.HTLC",
      "com.algorand.algosdk.templates.ContractTemplate$DataType",
      "com.algorand.algosdk.templates.ContractTemplate$1",
      "com.algorand.algosdk.templates.ContractTemplate",
      "com.algorand.algosdk.crypto.Address",
      "org.apache.commons.codec.binary.BaseNCodec",
      "org.apache.commons.codec.binary.Base32",
      "org.apache.commons.codec.Charsets"
    );
  }
}
