/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 29 07:04:03 GMT 2023
 */

package com.esri.geoportal.base.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.esri.geoportal.base.util.Val;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Val_ESTest extends Val_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Long long0 = new Long(1066L);
      Long long1 = Val.chkLong("1", long0);
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(7);
      Integer integer1 = Val.chkInt("1", integer0);
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Double double0 = new Double(0.0);
      Double double1 = Val.chkDbl("31%3F*8%7F%23FeH", double0);
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = Val.urlEncode("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = Val.unescapeUnicode("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = Val.unescapeOctalToUnicode("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = Val.unescapeOctal("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = Val.unescapeNunmericEntity("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = Val.unescapeHtml4("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = Val.unescape("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = Val.trim("31?*8#FeH");
      assertEquals("31?*8#FeH", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = Val.chkStr((String) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Long long0 = Val.chkLong("", (Long) null);
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = Val.chkInt(":BPFF5@irM6'U{", (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer((-5080));
      Integer integer1 = Val.chkInt("", integer0);
      assertEquals((-5080), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(132);
      Integer integer1 = Val.chkInt("", integer0);
      assertEquals(132, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Double double0 = Val.chkDbl((String) null, (Double) null);
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Val.UNICODE = null;
      // Undeclared exception!
      try { 
        Val.unescapeUnicode("'p>Sl");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.esri.geoportal.base.util.Val", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Val.NUMERIC = null;
      // Undeclared exception!
      try { 
        Val.unescapeNunmericEntity("Z<w@~Mh@r6@Bfg`y");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.esri.geoportal.base.util.Val", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Val.octalPattern = null;
      // Undeclared exception!
      try { 
        Val.unescape("VOrGIWFlltr1");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.esri.geoportal.base.util.Val", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = Val.unescapeHtml4("e%S*");
      assertEquals("e%S*", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = Val.trim((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = Val.trim("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String string0 = Val.chkStr("e%S*", "e%S*");
      assertEquals("e%S*", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String string0 = Val.chkStr((String) null, "true");
      assertEquals("true", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = Val.unescape("&mdash;");
      assertEquals("\u2014", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String string0 = Val.unescape((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String string0 = Val.unescapeOctalToUnicode("&#_.");
      assertEquals("&#_.", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String string0 = Val.unescapeOctalToUnicode((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String string0 = Val.unescapeUnicode("'p>Sl");
      assertEquals("'p>Sl", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String string0 = Val.unescapeUnicode((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String string0 = Val.unescapeOctal("VOrGIWFlltr1");
      assertEquals("VOrGIWFlltr1", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      String string0 = Val.unescapeOctal((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      String string0 = Val.unescapeNunmericEntity("z4u`?N7I0'v*gk|8");
      assertEquals("z4u`?N7I0'v*gk|8", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      String string0 = Val.unescapeNunmericEntity((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String string0 = Val.unescapeHtml4((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      String string0 = Val.urlEncode("&mdash;");
      assertEquals("%26mdash%3B", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      String string0 = Val.urlEncode((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      String[] stringArray0 = Val.tokenize("can't reindex without a destination type!", "true", false);
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      String[] stringArray0 = Val.tokenize((String) null, (String) null, false);
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String[] stringArray0 = Val.tokenize("&mdash;", "Ac", true);
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      // Undeclared exception!
      try { 
        Val.base64Encode(byteArray0, "0");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.UnsupportedEncodingException: 0
         //
         verifyException("com.esri.geoportal.base.util.Val", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      String string0 = Val.base64Encode(byteArray0, (String) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      String string0 = Val.base64Encode(byteArray0, "");
      assertEquals("AAA=", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      String string0 = Val.base64Encode((byte[]) null, "N>7MzK");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      String string0 = Val.chkStr("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Long long0 = Long.getLong("&supe;", (-2049L));
      Long long1 = Val.chkLong("&supe;", long0);
      assertEquals((-2049L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Long long0 = new Long(0L);
      Long long1 = Val.chkLong("", long0);
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Long long0 = new Long(1L);
      Long long1 = Val.chkLong((String) null, long0);
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = Val.chkInt("", integer0);
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Integer integer0 = new Integer(7);
      Integer integer1 = Val.chkInt((String) null, integer0);
      assertEquals(7, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Double double0 = new Double((double) (byte)0);
      Double double1 = Val.chkDbl("", double0);
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Double double0 = new Double(0.0);
      Double double1 = Val.chkDbl("-1", double0);
      assertEquals((-1.0), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Double double0 = new Double(318.030952613832);
      Double double1 = Val.chkDbl((String) null, double0);
      assertEquals(318.030952613832, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      boolean boolean0 = Val.chkBool("VOrGIWFlltr1", true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      boolean boolean0 = Val.chkBool("0", true);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      boolean boolean0 = Val.chkBool("n", false);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      boolean boolean0 = Val.chkBool("y", false);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      boolean boolean0 = Val.chkBool("1", false);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      boolean boolean0 = Val.chkBool((String) null, true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Val val0 = new Val();
  }
}
