/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 29 07:05:10 GMT 2023
 */

package com.esri.geoportal.base.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Val_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.esri.geoportal.base.util.Val"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Val_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.text.translate.AggregateTranslator",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.lang3.Range$ComparableComparator",
      "org.apache.commons.text.translate.EntityArrays",
      "org.apache.commons.text.translate.OctalUnescaper",
      "org.apache.commons.text.translate.CharSequenceTranslator",
      "org.apache.commons.text.translate.CsvTranslators$CsvUnescaper",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.text.translate.UnicodeUnescaper",
      "org.apache.commons.text.translate.NumericEntityEscaper",
      "com.esri.geoportal.base.util.Val",
      "org.apache.commons.lang3.Range",
      "org.apache.commons.io.file.PathVisitor",
      "org.apache.commons.text.translate.UnicodeUnpairedSurrogateRemover",
      "org.apache.commons.text.translate.SinglePassTranslator",
      "org.apache.commons.text.translate.JavaUnicodeEscaper",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "org.apache.commons.text.StringEscapeUtils",
      "org.apache.commons.text.translate.CodePointTranslator",
      "org.apache.commons.text.translate.NumericEntityUnescaper",
      "org.apache.commons.text.StringEscapeUtils$XsiUnescaper",
      "org.apache.commons.text.StringEscapeUtils$Builder",
      "org.apache.commons.lang3.Validate",
      "org.apache.commons.text.translate.NumericEntityUnescaper$OPTION",
      "org.apache.commons.text.translate.CsvTranslators$CsvEscaper",
      "org.apache.commons.text.translate.LookupTranslator",
      "org.apache.commons.text.translate.UnicodeEscaper",
      "org.apache.commons.io.file.PathFilter"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Val_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.text.translate.CharSequenceTranslator",
      "org.apache.commons.text.translate.NumericEntityUnescaper$OPTION",
      "org.apache.commons.text.translate.NumericEntityUnescaper",
      "org.apache.commons.lang3.ArrayUtils",
      "com.esri.geoportal.base.util.Val",
      "org.apache.commons.text.translate.EntityArrays",
      "org.apache.commons.lang3.Range",
      "org.apache.commons.lang3.Range$ComparableComparator",
      "org.apache.commons.text.StringEscapeUtils$XsiUnescaper",
      "org.apache.commons.text.StringEscapeUtils",
      "org.apache.commons.lang3.Validate",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.OrFileFilter"
    );
  }
}
