/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jul 31 10:10:59 GMT 2023
 */

package com.korpodrony.validation;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Validator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.korpodrony.validation.Validator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Validator_ESTest_scaffolding.class.getClassLoader() ,
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.assertj.core.internal.bytebuddy.matcher.ElementMatcher",
      "org.assertj.core.internal.bytebuddy.description.type.TypeDescription$AbstractBase",
      "org.assertj.core.internal.bytebuddy.description.type.TypeDefinition",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$AbstractBase",
      "org.assertj.core.internal.bytebuddy.description.NamedElement$WithRuntimeName",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "org.apache.commons.lang3.StringUtils",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "org.assertj.core.internal.bytebuddy.description.NamedElement",
      "org.assertj.core.internal.bytebuddy.description.TypeVariableSource",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "org.apache.commons.lang3.CharSequenceUtils",
      "com.korpodrony.validation.Validator",
      "org.assertj.core.internal.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "org.assertj.core.internal.bytebuddy.description.type.TypeList$Generic",
      "org.assertj.core.internal.bytebuddy.implementation.EqualsMethod",
      "org.assertj.core.internal.bytebuddy.implementation.bytecode.ByteCodeAppender",
      "org.assertj.core.internal.bytebuddy.description.TypeVariableSource$AbstractBase",
      "org.assertj.core.internal.bytebuddy.description.ByteCodeElement",
      "org.assertj.core.internal.bytebuddy.implementation.HashCodeMethod$OffsetProvider",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable",
      "org.assertj.core.internal.bytebuddy.dynamic.DynamicType$Builder",
      "org.assertj.core.internal.bytebuddy.implementation.HashCodeMethod",
      "org.assertj.core.internal.bytebuddy.implementation.bytecode.StackManipulation",
      "org.assertj.core.internal.bytebuddy.description.type.TypeDescription$ForLoadedType",
      "org.assertj.core.internal.bytebuddy.description.type.TypeDescription",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$ForFieldDescription",
      "org.assertj.core.internal.bytebuddy.matcher.FilterableList",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "org.assertj.core.internal.bytebuddy.description.annotation.AnnotationSource",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "org.assertj.core.internal.bytebuddy.build.Plugin",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "org.assertj.core.internal.bytebuddy.description.DeclaredByType",
      "org.apache.commons.lang3.math.NumberUtils",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$ForMethodDescription",
      "org.assertj.core.internal.bytebuddy.implementation.Implementation",
      "org.assertj.core.internal.bytebuddy.description.ModifierReviewable$ForParameterDescription"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Validator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.korpodrony.validation.Validator",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.lang3.math.NumberUtils",
      "org.apache.commons.lang3.CharSequenceUtils"
    );
  }
}
